### ISSUE TITLE
Teste de Integração com o Trello QA

### ISSUE THREAD

**Issue by kizylirio** [kizylirio/zordontest#5]
Aqui nós temos a descrição da Issue que deve ser testada

**Comment by kizylirio** [comment]
Aqui temos o exemplo do que foi feito

**Comment by kizylirio** [comment]
Tenho o exemplo de uma mention @vtexintegration

**Comment by vtexintegration** [comment]
[Trello task was created!](https://trello.com/c/BQQO56Je)
