### ISSUE TITLE
Teste Integração QA

### ISSUE THREAD

**Issue by kizylirio** [kizylirio/zordontest#8]
Exemplo de Descrição

**Comment by kizylirio** [comment]
Exemplo de comentário

**Comment by vtexintegration** [comment]
[Trello task was created!](https://trello.com/c/gNzZ2DZw)

**Comment by kizylirio** [comment]
Teste funcionou :dancer:

**Comment by vtexintegration** [comment]
Funcionou melhor que o esperado

By: Kizy Lopes
